import Head from "next/head";
import Image from "next/image";
import Login from "../components/Login";
import { useMoralis } from "react-moralis";
import Header from "../components/Header";
import Messages from "../components/Messages";

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();

  if (!isAuthenticated) return <Login />;

  return (
    <div className="h-screen  bg-gradient-to-b from-black to-fuchsia-900 overflow-y-scroll">
      <Head>
        <title>Metaverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
        <div className="max-w-screen-2xl overflow-scroll mx-auto">
          <Header/>

         <Messages/>
        </div>
  

    </div>
  );
}
